build.sbt, docker-compose.yml, project/InfrastructureHelper.scala
Adds the following SBT commands: 
- `startPostgres`
- `stopPostgres`
- `startMySQL`
- `stopMySQL`
- `startMsSQL`
- `stopMsSQL`
- `startOracle`
- `stopOracle`
These commands make calls to Docker-Compose to start up and shutdown the appropriate database
Tackles #18, #19,  #20, #21
=> Add local database infrastructure using Docker-Compose

project/BuildHelper.scala, zio-sql/jvm/src/main/scala/Sql.scala
I think we can simplify the signature of `narrow` in `FunctionDef` from:
```scala
def narrow[A1 <: A, C](implicit ev: A1 =:= C): FunctionDef[C, B]
```
to:
```scala
def narrow[C](implicit ev: C <:< A): FunctionDef[C, B]
```
This also allows us to simplify the type signature of the `FunctionCallN` variants to eliminate the `A1` type parameter and only require implicit evidence that `(P1, P2) <:< A`, which should improve type inference.
Other changes just from running `fmt`.
=> Simplify Type Signatures in FunctionDef

project/BuildHelper.scala, zio-sql/jvm/src/main/scala/Sql.scala
By moving `as` and `in` to implicit syntax we can recover covariance on output types of `Expr` and `FunctionDef`.
=> Make Expr Covariant on Output Type

zio-sql/jvm/src/main/scala/Sql.scala
Based on the following docs:
- https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html
- https://www.postgresql.org/docs/12/functions-math.html
- https://docs.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql?view=sql-server-ver15
- https://docs.oracle.com/database/121/SQLRF/functions002.htm#SQLRF51178
mathematical functions supported by all 4 servers (mysql, postgresql, sql sever and oracle) are:
- ABS()	  
- ACOS()	  
- ASIN()	  
- ATAN()	  
- COS()	  
- EXP()	  
- POWER()	  
- ROUND()	  
- SIGN()	  
- SIN()	  
- SQRT()	  
- TAN()	
There is also  `ATAN2()` but for SQL Server the name of this function is  `ATN2`.
A similar situation is for `TRUNCATE` function. Its name for Mysql is `TRUNCATE`, for Postgresql and Oracle it is `trunc` but for SQL …
=> Add mathematical functions

zio-sql/jvm/src/main/scala/Sql.scala
For #5 
Based on the following docs:
- https://dev.mysql.com/doc/refman/8.0/en/string-functions.html
- https://www.postgresql.org/docs/12/functions-string.html
- https://docs.microsoft.com/en-us/sql/t-sql/functions/string-functions-transact-sql?view=sql-server-ver15
- https://docs.oracle.com/database/121/SQLRF/functions002.htm#SQLRF51178
string functions supported by all 4 servers (mysql, postgresql, sql sever and oracle) are:
- `ASCII`	 
- `CONCAT`	 
- `LOWER`	 
- `LTRIM`	 
- `REPLACE`  
- `RTRIM`	 
- `TRIM`	 
- `UPPER`
=> Add string functions

zio-sql/jvm/src/main/scala/Sql.scala
There are many date&time functions but only `CURRENT_TIMESTAMP()` is supported by Postgres, MySQL, SQL Server and Oracle.
- https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html
- https://www.postgresql.org/docs/12/functions-datetime.html
- https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15
- https://docs.oracle.com/database/121/SQLRF/functions002.htm#SQLRF51180
For #5
=> Add current_timestamp function

zio-sql/jvm/src/main/scala/Sql.scala, zio-sql/jvm/src/test/scala/TestBasicSelectSpec.scala
Implicit conversion from Expr[F, A, B] to Selection[F, A, SelectionSet.Cons[A, B, SelectionSet.Empty]]
to support select with default column names:
```scala
val userId :*: dob :*: fName :*: lName :*: _ = userTable.columns
val basicSelect = select { fName ++ lName } from userTable
```
Would it be possible to modify exprName to allow select arbitrary expressions with an auto generated name ?
```scala
def exprName[F, A, B](expr: Expr[F, A, B]): Option[String] =
expr match {
case Expr.Source(_, c) => Some(c.name)
case _ => None
}
```
=> Support selecting columns using existing column names

zio-sql/jvm/src/main/scala/Sql.scala, zio-sql/jvm/src/main/scala/zio/sql/Examples.scala
partially fixes #37 - requires `deleteFrom` to be a source table, doesn't address how we support deleting from a join; raised #43 for this
=> Force delete from source

zio-sql/jvm/src/main/scala/Sql.scala, zio-sql/jvm/src/main/scala/zio/sql/Examples.scala, zio-sql/jvm/src/main/scala/zio/sql/Renderable.scala
very naive attempt at #8, @jdegoes can you please review?
- no escaping for sql injection
- values not rendered correctly
- no group by
- no order by
- selects in joins aren't qualified by the table they're from (which is a problem if the same column name exists in both tables being joined)
issues discovered:
- aggregations go boom at runtime (unimplemented implicit defs)
- offset doesn't seem to be supported by sql server or oracle unless you use `fetch first/next`. In sql server this is considered part of `order by` and mysql doesn't support `fetch first`. I think we need a dialect as part of the signatures for `render` and `renderBuilder` to deal with dialect specific issues like top vs. limit vs. rownum (line 353)
- in an update statement, `set` isn't required to be non-empty. I've …
=> WIP Add Rendering

build.sbt
This fixes wrong subprojects configuration that causes all artifacts to be published under the same name.
=> Fix bad naming of published artifacts

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
Add GCD, LCM, CBRT, Degrees, Div, Factorial to PostgresFunctionDef
Fixes: #172 , #171 , #170 , #169 , #168 , #167
=> Add GCD, LCM, CBRT, Degrees, Div, Factorial to PostgresFunctionDef

jdbc/src/main/scala/zio/sql/jdbc.scala
=> Fill the missing date/time related decoding in ReadExecutor

core/jvm/src/main/scala/zio/sql/Sql.scala, core/jvm/src/main/scala/zio/sql/delete.scala, core/jvm/src/test/scala/zio/sql/GroupByHavingSpec.scala, core/jvm/src/test/scala/zio/sql/ProductSchema.scala, core/jvm/src/test/scala/zio/sql/TestBasicSelectSpec.scala, examples/src/main/scala/Example1.scala, jdbc/src/main/scala/zio/sql/JdbcRunnableSpec.scala, jdbc/src/main/scala/zio/sql/jdbc.scala, postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresModuleTest.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresRunnableSpec.scala, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerModule.scala
fixes: https://github.com/zio/zio-sql/issues/150
This PR adds renderDelete for PostgreSQL 
- implements `DeleteExecutor`
- makes `execute` return `Int`, the number of deleted rows
- adds `all` combinator to `DeleteBuilder` as `WHERE` clause in `DELETE FROM` is optional
- ~moves rendering functions into `Renderer` to be reusable across `render{Read | Delete | etc...}`~
- adds tests
=> Postgres render delete

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
That's my first PR ever on open source project, so just let me know if I messed up something obvious. My concerns:
1. FunctionCall0 was already implemented, so I rebased it on changes here: https://github.com/zio/zio-sql/pull/286/
2. I followed similar design like in Random(), but honestly I'm not convinced to using `select(PgClientEncoding()) from customers`. IMO it should be fine to just use it without 'from': `SELECT pg_client_encoding();` but I had no idea how to achieve that.
=> Add 'pg_client_encoding' function to PostgresModule #191

core/jvm/src/main/scala/zio/sql/delete.scala, core/jvm/src/main/scala/zio/sql/update.scala, jdbc/src/main/scala/zio/sql/transaction.scala
I am not entirely sure why, but Scala 3 needs these modules to be available in order to compile. Strange that Scala 2 does not also require them :-) It could of course also be a bug in Scala 3 so take this with a grain of salt :-)
=> add missing dependencies to module pattern

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/DeleteSpec.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresModuleSpec.scala
- Fix commented tests
- Remove println
- Change query syntax to dot-based
=> Postgres specs cleanup

build.sbt, core/shared/src/test/scala/zio-sql/HelloWorldSpec.scala, jdbc/src/main/scala/zio/sql/ConnectionPool.scala, jdbc/src/main/scala/zio/sql/ConnectionPoolConfig.scala, jdbc/src/main/scala/zio/sql/SqlDriverLiveModule.scala, jdbc/src/main/scala/zio/sql/TransactionModule.scala, jdbc/src/main/scala/zio/sql/jdbc.scala, jdbc/src/test/scala/zio/sql/JdbcRunnableSpec.scala, mysql/src/test/scala/zio/sql/TestContainer.scala, mysql/src/test/scala/zio/sql/mysql/DeleteSpec.scala, mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala, mysql/src/test/scala/zio/sql/mysql/MysqlModuleTest.scala, mysql/src/test/scala/zio/sql/mysql/MysqlRunnableSpec.scala, mysql/src/test/scala/zio/sql/mysql/TransactionSpec.scala, postgres/src/test/scala/zio/sql/TestContainer.scala, postgres/src/test/scala/zio/sql/postgresql/DeleteSpec.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresModuleSpec.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresRunnableSpec.scala, postgres/src/test/scala/zio/sql/postgresql/TransactionSpec.scala
This PR does the minimal amount of changes to get this library too compile against the latest ZIO 2.0 milestone release.
I can include the implicit `ZTraceElement` and updating any ZIO returning functions to take in parameters by name in this PR or hold off and do it in a followup PR once this is merged.
=> Make it compile with ZIO 2.0

mysql/src/main/scala/zio/sql/mysql/MysqlSqlModule.scala, mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
=> rand function for MySql added

oracle/src/main/scala/zio/sql/oracle/OracleRenderModule.scala, oracle/src/test/scala/zio/sql/oracle/OracleModuleSpec.scala, oracle/src/test/scala/zio/sql/oracle/OracleRunnableSpec.scala, oracle/src/test/scala/zio/sql/oracle/ShopSchema.scala, oracle/src/test/scala/zio/sql/oracle/TestContainer.scala
implements #156 
I had to specially deal with boolean values, as Oracle does support them only via smallint (or char).
=> Render delete for oracle

.github/workflows/ci.yml, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerRenderModule.scala, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerSqlModule.scala, sqlserver/src/test/resources/db_schema.sql, sqlserver/src/test/scala/zio/sql/sqlserver/DbSchema.scala, sqlserver/src/test/scala/zio/sql/sqlserver/SqlServerModuleSpec.scala
SqlServer limitations:
DATETIME2  ISO format: YYYY-MM-DDThh:mm:ss[.nnnnnnn] , precision 0 to 7 digits, with an accuracy of 100ns (default 7)
DATETIMEOFFSET ISO format: YYYY-MM-DDThh:mm:ss[.nnnnnnn][{+|-}hh:mm], precision 0 to 7 digits, with an accuracy of 100ns (default 7)
TIME format: hh:mm[:ss][.fractional seconds]  precision 0 to 7 digits, with an accuracy of 100ns (default 7)
DATETIME is not supported. ISO fromat: YYYY-MM-DDThh:mm:ss[.mmm], Rounded to increments of .000, .003, or .007 seconds. 
Duration is not available in MSSQL.
DECIMAL can be used as analog of BigDecimal. Maximum precision 38 digits (default 18).
=> Mapping of Schema types to corresponding SqlServer types for Insert case

build.sbt, macros/src/main/scala/zio/sql/macros/tablelike.scala
This fixes the problem with publish phase failing in v0.1.0 release because zio-sql-macros_2.12 module was missing.
=> Fix 0.1.0 release

.github/workflows/ci.yml, build.sbt, core/jvm/src/main/scala/zio/sql/features.scala, core/jvm/src/main/scala/zio/sql/select.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresSqlModuleSpec.scala, project/BuildHelper.scala, project/plugins.sbt, sbt, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerSqlModule.scala, sqlserver/src/test/scala/zio/sql/sqlserver/SqlServerModuleSpec.scala
- update Scala versions for 2.12 and 2.13
- @silence invalid warnings introduced by Scala >= 2.13.9
- set compiler options in line with the core ZIO project
=> Remove sbt warnings and update Scala versions

build.sbt, jdbc-hikaricp/src/test/scala/zio/sql/MySqlTestContainer.scala, mysql/src/test/scala/zio/sql/mysql/MysqlRunnableSpec.scala
Latest MySQL removed `--skip-host-cache` flag but testcontainers still try to use it causing:
```
2024-03-29T15:45:29.779392Z 0 [ERROR] [MY-000068] [Server] unknown option '--skip-host-cache'.
2024-03-29T15:45:29.779894Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
2024-03-29T15:45:29.779907Z 0 [ERROR] [MY-010119] [Server] Aborting
```
I've hardcoded the last MySQL version that has this flag.
=> Hardcode MySQL version
