zio/zio-sql

README.md
Feel free to close this Pull Request if you don't think this is a relevant addition to the README.
=> Suggestion: change README to give emphasis to syntax difference to Slick

zio-sql/jvm/src/main/scala/Sql.scala
For #6 
@jdegoes is it enough?
=> Add missing aggregation functions

zio-sql/jvm/src/main/scala/Sql.scala, zio-sql/jvm/src/main/scala/zio/sql/Examples.scala
fixes #39. Much easier than I was expecting!
=> don't require all tables from join in select

zio-sql/jvm/src/main/scala/Sql.scala
Fix https://github.com/zio/zio-sql/issues/3
There's a lot more but every database does something differently.
=> add binary operators

zio-sql/jvm/src/main/scala/zio/sql/Examples.scala
#28 has been fixed so we don't need aliases everywhere.
=> tidy up examples (#28 fixed)

zio-sql/jvm/src/main/scala/Sql.scala, zio-sql/jvm/src/test/scala/zio/sql/GroupByHavinSpec.scala, zio-sql/jvm/src/test/scala/zio/sql/GroupByHavingSpec.scala
Fix #50 add support for `having` clause
=> add having clause

core/jvm/src/main/scala/Sql.scala, jdbc/src/main/scala/zio/sql/jdbc.scala
Here is a proposition to prevent on type level TOption[TOption]
* add NotNull
* use NotNull to prevent nesting Nullable
* rename TOption => Nullable
=> add NotNull to prevent nesting Nullable

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Support for starts_with in PostgreSQL module

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
Fixes #179
Fixes #187 
Fixes #203 
Fixes #186 
Fixes #175 
Fixes #174
=> Add support for trunc, length, translate, left, right, radians, min_scale

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
This PR addresses:  #233, #232, #231
=> Add postgres test for round, power, mod

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
This PR addresses #234. Also changes sign to return Int type
=> Add tests for sign function, change sign to return Int type

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Fix And Add Tests For Width_Bucket And Ascii

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Adding octet_length TC

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> #242 Postgres TC for lower function

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Add test for 'Ceil' function for PostgreSQL

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> add trim_scale function for Postgres

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Add test for 'Exp' function for PostgreSQL

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Add test for 'Ln' function for PostgreSQL

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Support for PostgreSQL 'repeat', 'reverse'

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> add initcap

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerModule.scala
=> Add current_date function

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Fix and add Tests For character length and concat

core/jvm/src/main/scala/zio/sql/expr.scala, postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> Add 'md5' function to PostgresModule

core/jvm/src/main/scala/zio/sql/Sql.scala, core/jvm/src/test/scala/zio/sql/GroupByHavingSpec.scala, core/jvm/src/test/scala/zio/sql/ProductSchema.scala, core/jvm/src/test/scala/zio/sql/TestBasicSelectSpec.scala, examples/src/main/scala/Example1.scala, jdbc/src/main/scala/zio/sql/jdbc.scala, postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, sqlserver/src/main/scala/zio/sql/sqlserver/SqlServerModule.scala
=> Implement live layer for UpdateExecutor

jdbc/src/main/scala/zio/sql/JdbcRunnableSpec.scala, jdbc/src/main/scala/zio/sql/jdbc.scala, jdbc/src/main/scala/zio/sql/transaction.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresModuleTest.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresRunnableSpec.scala
=> transactions

postgres/src/main/scala/zio/sql/postgresql/PostgresModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
https://github.com/zio/zio-sql/issues/213
=> Add postgresql functions: now, statement_timestamp and transaction_timestamp

postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
Fix for timestamp tests https://github.com/zio/zio-sql/issues/326
=> fix flaky timestamp tests

README.md, core/jvm/src/main/scala/zio/sql/Sql.scala, examples/src/main/scala/Example1.scala, examples/src/main/scala/zio/sql/Examples.scala, postgres/src/test/scala/zio/sql/postgresql/DeleteSpec.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresModuleSpec.scala, project/BuildHelper.scala
=> Fix scala 2.12 `deleteFrom` signature problem

build.sbt, project/BuildHelper.scala, project/plugins.sbt
- remove sbt-dotty
- update Dotty version
- comply with sbt 1.5 format
- remove Scala 2.11 configuration
=> Build configuration refactor

README.md, docs/overview/index.md, sqlserver/src/test/scala/zio/sql/sqlserver/SqlServerModuleSpec.scala
@jczuchnowski I added some documentation for inserts and subqueries. Please check it when you have a chance.
=> Documentation for inserts & subqueries

build.sbt, core/jvm/src/test/scala/zio/sql/ArithmeticOpsSpec.scala, core/jvm/src/test/scala/zio/sql/BitwiseOpSpec.scala, core/jvm/src/test/scala/zio/sql/GroupByHavingSpec.scala, core/jvm/src/test/scala/zio/sql/LogicalOpsSpec.scala, core/jvm/src/test/scala/zio/sql/PredicateOpSpec.scala, core/jvm/src/test/scala/zio/sql/TestBasicSelectSpec.scala, core/shared/src/test/scala/zio-sql/HelloWorldSpec.scala, jdbc/src/main/scala/zio/sql/TransactionModule.scala, jdbc/src/main/scala/zio/sql/jdbc.scala, jdbc/src/test/scala/zio/sql/JdbcRunnableSpec.scala, mysql/src/test/scala/zio/sql/TestContainer.scala, mysql/src/test/scala/zio/sql/mysql/MysqlRunnableSpec.scala, postgres/src/test/scala/zio/sql/TestContainer.scala, postgres/src/test/scala/zio/sql/postgresql/PostgresRunnableSpec.scala, sqlserver/src/test/scala/zio/sql/TestContainer.scala, sqlserver/src/test/scala/zio/sql/sqlserver/SqlServerRunnableSpec.scala
@jczuchnowski 
Changes:
1. removed "provided" from zio & zio-schema dependencies
2. run scalafix zio 2.0 migration
=> scalafix zio 2.0 migration

build.sbt, jdbc/src/main/scala/zio/sql/ConnectionPool.scala, jdbc/src/test/scala/zio/sql/ConnectionPoolSpec.scala, jdbc/src/test/scala/zio/sql/TestContainer.scala
=> Ensure that connections are released after interrupt

postgres/src/main/scala/zio/sql/postgresql/PostgresSqlModule.scala, postgres/src/test/scala/zio/sql/postgresql/FunctionDefSpec.scala
=> support for gen_random_uuid function of PostgreSQL

mysql/src/test/scala/zio/sql/mysql/FunctionDefSpec.scala
https://github.com/zio/zio-sql/issues/679
=> #679 Clean up FunctionDefSpec

examples/src/main/scala/zio/sql/Examples.scala
=> insert examples for tuple and case class with scema derive

mysql/src/main/scala/zio/sql/mysql/MysqlRenderModule.scala, mysql/src/main/scala/zio/sql/mysql/MysqlSqlModule.scala, mysql/src/test/resources/shop_schema.sql, mysql/src/test/scala/zio/sql/mysql/MysqlModuleSpec.scala, mysql/src/test/scala/zio/sql/mysql/ShopSchema.scala
- Address https://github.com/zio/zio-sql/issues/158
- Mostly adapted from the Postgres implementation.
=> Implement renderInsert for MySQL
